spring:
  datasource:
#    url: jdbc:postgresql://postgres:GqkUUXPWfthwOvFVsDCooiNxXChnGMJx@centerbeam.proxy.rlwy.net:11756/railway
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
server:
  port: ${PORT:8080}